kind: PersistentVolume
apiVersion: v1
metadata:
  name: fcrepo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcrepo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: fcrepo
  name: fcrepo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: fcrepo
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: fcrepo
  name: fcrepo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fcrepo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: fcrepo
    spec:
      containers:
      - image: yinlinchen/fcrepo-images:fcrepo-5.0.2
        name: fcrepo
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: fcrepo-persistent-storage
          mountPath: /mnt/ingest
        resources: {}
      volumes:
      - name: fcrepo-persistent-storage
        persistentVolumeClaim:
          claimName: fcrepo-pv-claim
status: {}
